sonar.projectKey=porturl_porturl-web
sonar.organization=porturl

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=porturl-web

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# TypeScript support
sonar.typescript.tsconfigPath=tsconfig.json
